CREATE TABLE PROJECT (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100),
    Description NVARCHAR(MAX)
);

CREATE TABLE USER_STORY (
    Id INT PRIMARY KEY IDENTITY(1,1),
    ProjectId INT FOREIGN KEY REFERENCES PROJECT(Id),
    Description NVARCHAR(MAX),
    State INT,
    Priority INT
);

CREATE TABLE TASK (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserStoryId INT FOREIGN KEY REFERENCES USER_STORY(Id),
    Description NVARCHAR(MAX),
    State INT,
    Priority INT,
    Difficulty INT,
    Category NVARCHAR(50)
);

CREATE TABLE PERSON (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100),
    Role NVARCHAR(50)
);

CREATE TABLE PROJECT_TEAM (
    ProjectId INT FOREIGN KEY REFERENCES PROJECT(Id),
    PersonId INT FOREIGN KEY REFERENCES PERSON(Id),
    PRIMARY KEY (ProjectId, PersonId)
);

CREATE TABLE TASK_ASSIGNMENT (
    TaskId INT FOREIGN KEY REFERENCES TASK(Id),
    PersonId INT FOREIGN KEY REFERENCES PERSON(Id),
    PRIMARY KEY (TaskId, PersonId)
);